### ISSUE TITLE
Error when using "parcel" package instead of "parcel-bundler"

### ISSUE THREAD

**Issue by oliver-hoff** [VladimirMikulic/parcel-plugin-custom-dist-structure#21]
**Describe the bug**
I have a complex project with React.lazy imports. I follow the instructions for config as explained in my package.json (only using the js and images options)

**How it happened?**
After installing the plugin and building, I get the error: The "path" argument must be of type string. Received type undefined

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15
 - Parcel version: 1.2.1
 - Plugin version: latest

**Plugin configuration object:**

`
  "customDistStructure": {
    "config": {
      ".js": "js",
      "images": [
        ".jpg",
        ".png"
      ]
    }
  }
`

**Comment by VladimirMikulic** [comment]
Hi Oliver. Thank you for reporting this issue. Could you please post a complete call-stack here. Thank you.

**Comment by oliver-hoff** [comment]
Wow that was fast! Thanks for responding. Here is the stack trace:

`
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.relative (path.js:1171:5)
    at fileDependeciesPaths.forEach.depPath (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/FileProcessor.js:69:29)
    at Array.forEach (<anonymous>)
    at FileProcessor.updateDependecies (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/FileProcessor.js:60:26)
    at FileProcessor.processFile (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/FileProcessor.js:36:10)
    at OutputGenerator.processFiles (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/OutputGenerator.js:37:21)
    at OutputGenerator.generateOutputFolder (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/OutputGenerator.js:20:12)
    at Bundler.bundler.on.bundle (/Users/oliverhoffman/Projects/seliom/web/client/node_modules/parcel-plugin-custom-dist-structure/lib/index.js:39:21)
    at Bundler.emit (events.js:187:15)
`

**Comment by VladimirMikulic** [comment]
That's strange. Could you please try the previous version (1.1.9)?
It's a minor change but I would like to check if it works alright.

Also, does the lazy load work without my plugin?
You might find this useful https://github.com/parcel-bundler/parcel/issues/2193

**Comment by VladimirMikulic** [comment]
You can probably ignore my previous comment :)
I think I've figured out the problem. Almost all tests fail on version 1.2.1.
This wasn't a surprise for me since that version is 2+ years old.
It's completely different from 1.12.4 (current latest).

Could you possibly bump Parcels version to 1.12.4? If you don't have some other old version-specific configs/plugins, it shouldn't break anything.

Thank you.

**Comment by oliver-hoff** [comment]
Ok thank you! I will try that. I was thinking perhaps the aliases I am using might also be the cause, but its much more likely to be what you suggested. I will report back :)

**Comment by VladimirMikulic** [comment]
So, did it work? :)

**Comment by oliver-hoff** [comment]
Sorry! I have been swamped with work and haven’t tried. Will report back tonight so we can close the issue. Thanks for all your help!

**Comment by VladimirMikulic** [comment]
No problem, take your time :)

**Comment by miguelcabanzo** [comment]
Not sure if related, but I got a similar error on build using 1.12.4:

Plugin parcel-plugin-custom-dist-structure failed to initialize: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined

**Comment by VladimirMikulic** [comment]
Could you please check out #22 and see if the error persists?

**Comment by miguelcabanzo** [comment]
Unfortunately the patch didn't solve the issue, dev/prod still throw the same error.

**Comment by VladimirMikulic** [comment]
Could you please post your OS, project structure & config object so I can identify the issue?

**Comment by miguelcabanzo** [comment]
Sure, here they are:

Mac OS Catalina 10.15.4
```
dist
src
|- img
   |- img1.jpg
   |- img2.jpg
   |- ...
|- index.html
|- index.js
|- lib.js
|- style.css
package.json
```
```
"customDistStructure": {
   "config": {
      "rscs": [
        ".jpg",
        ".png",
        ".gif",
        ".svg"
      ]
   }
}
```

**Comment by VladimirMikulic** [comment]
Hi @miguelcabanzo.
I've updated the patch. Could you please follow the instructions and try to see if it works?

Thank you.

**Comment by VladimirMikulic** [comment]
I've released v1.1.11. Could you please check if the issue persists?

**Comment by miguelcabanzo** [comment]
got a chance to finally test it today @VladimirMikulic, unfortunately v1.1.11 still returns `TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string.`

**Comment by VladimirMikulic** [comment]
@miguelcabanzo could you post the complete call-stack? Thanks.

**Comment by miguelcabanzo** [comment]
Sure:
```
Plugin parcel-plugin-custom-dist-structure failed to initialize: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Module.require (internal/modules/cjs/loader.js:1012:3)
    at require (/Users/miguel/.nvm/versions/node/v12.16.3/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/miguel/Sites/boilerplate-parcel/node_modules/parcel-plugin-custom-dist-structure/lib/index.js:8:19)
    at Module._compile (/Users/miguel/.nvm/versions/node/v12.16.3/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/miguel/.nvm/versions/node/v12.16.3/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

**Comment by VladimirMikulic** [comment]
@miguelcabanzo could you please set up an example repo which reproduces this error? Thank you.

**Comment by VladimirMikulic** [comment]
@miguelcabanzo @oliver-hoff I think I know what this issue is about.
Both of you are probably using `parcel` package and not `parcel-bundler` package.
They are essentially the same but exist with different names for some historic reasons.

My plugin was only supporting `parcel-bundler`.
@cxa spotted this issue and submitted a patch.

v1.1.13 has been published which includes this patch. Could you please try it and let me know if the issue is resolved?
Thank you.
