### ISSUE TITLE
Error trying to compile SASS files on Windows 64-bit

### ISSUE THREAD

**Issue by clovis-rosa** [VladimirMikulic/parcel-plugin-custom-dist-structure#3]
Hi Vladimir! I'm open a new issue as it's a different error. The plugin works when its first started, but once I save any changes the following error pops up:
You can find the test project here: https://github.com/clovis-rosa/landingpage_test

`Server running at http://localhost:1234 
√  Built in 54ms.
×  ENOENT: no such file or directory, rename 'C:\landingpage_test\dist\styles.164d45a1.css' -> 'C:\landingpage_test\dist\css\styles.164d45a1.css'
    at Object.renameSync (fs.js:675:3)
    at AsyncFunction.module.exports.sync (C:\landingpage_test\node_modules\move-file\index.js:61:6)
    at moveFileSync (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\Utils.js:33:12)
    at FileProcessor.processFile (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\FileProcessor.js:24:5)
    at C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:47:21
    at Array.forEach (<anonymous>)
    at OutputGenerator.processFiles (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:39:11)
    at C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:34:12
    at Array.forEach (<anonymous>)
    at OutputGenerator.generateOutputFolder (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:13:40)
(node:22128) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (C:\landingpage_test\node_modules\ws\lib\websocket.js:314:19)
    at HMRServer.broadcast (C:\landingpage_test\node_modules\parcel-bundler\src\HMRServer.js:110:10)
    at HMRServer.emitError (C:\landingpage_test\node_modules\parcel-bundler\src\HMRServer.js:63:10)
    at Bundler.bundle (C:\landingpage_test\node_modules\parcel-bundler\src\Bundler.js:350:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Timeout._onTimeout (C:\landingpage_test\node_modules\parcel-bundler\src\Bundler.js:817:7)
(node:22128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

The only change I make in the JASON file was to address any "*.scss" file to "css" folder:

`{
  "name": "landingpage_test",
  "version": "1.0.0",
  "description": "Test project using 'parcel-plugin-custom-dist-structure' for ParcelJs.",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "clean": "rm dist/bundle.js",
    "start": "parcel src/index.html",
    "build-prod": "parcel build src/index.html"
  },
  "customDistStructure": {
    "config": {
      ".css": "css",
      ".scss": "css",
      ".js": "js",
      "images": [
        ".jpg",
        ".svg",
        ".png"
      ]
    },
    "options": {
      "development": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-custom-dist-structure": "^1.0.3",
    "sass": "^1.26.3"
  }
}
`

Cheers!

**Comment by VladimirMikulic** [comment]
Hi @clovis-rosa. You are using the version `1.0.3`. This has been fixed in the latest version (`1.0.4`).
Check it out :)

**Comment by clovis-rosa** [comment]
Hey, would you please consider reopen the issue and look at it?
It's happing in the Head of the compiled HTML, it's repeating the folder url - "/css/css/..."

`<link rel="stylesheet" href="/css/css/styles.164d45a1.css">`
`<script src="/js/js/styles.164d45a1.js"></script></head>`

`<link rel="stylesheet" href="/css/css/css/styles.164d45a1.css">`
`<script src="/js/js/js/styles.164d45a1.js"></script></head>`

**Comment by VladimirMikulic** [comment]
Good catch. I'll need to improve the development mode. Thank you.

**Comment by VladimirMikulic** [comment]
@clovis-rosa thanks again. This time the development mode has been thoroughly tested.
The new minor version `1.0.5` has been released. You can download and use it on your project.

Thank you.
