### ISSUE TITLE
Multiple entries support

### ISSUE THREAD

**Issue by ziven27** [VladimirMikulic/parcel-plugin-custom-dist-structure#6]
```json
{
    "build": "parcel build src/pages/*.html"
}
```
```bash
🚨  Cannot read property 'parentBundle' of null
    at DependencyGraph.get entryAssetPath [as entryAssetPath] (/Users/ziven27/Pro/yss-template/node_modules/parcel-plugin-custom-dist-structure/lib/DependencyGraph.js:74:35)
    at DependencyGraph.buildDependencyGraph (/Users/ziven27/Pro/yss-template/node_modules/parcel-plugin-custom-dist-structure/lib/DependencyGraph.js:13:33)
    at new DependencyGraph (/Users/ziven27/Pro/yss-template/node_modules/parcel-plugin-custom-dist-structure/lib/DependencyGraph.js:9:10)
    at Bundler.bundler.on.bundle (/Users/ziven27/Pro/yss-template/node_modules/parcel-plugin-custom-dist-structure/lib/index.js:17:19)
    at Bundler.emit (events.js:203:15)
    at Bundler.bundle (/Users/ziven27/Pro/yss-template/node_modules/parcel-bundler/src/Bundler.js:340:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

when i  have script in my package.json , it will show this error.
```json
{
    "build": "parcel build src/pages/index.html"
}
```

but this is ok.

**Comment by VladimirMikulic** [comment]
Hi @ziven27.
Thank you for reporting this issue. As of now, only one entry file is supported.
This feature will be available soon :)

**Comment by VladimirMikulic** [comment]
@oberonlai, as I promised here, is your most wanted feature :)
If you and @ziven27 could test this, it would be great!
The same steps as before.

1. Clone the project git clone https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure.git
2. Check out the test branch `git checkout feature/multiple-entries-support`
3. Make it available globally on your system `npm link`
4. After running npm link, you'll get the absolute path to the package -> copy it
5. Enter the another project and run `npm i -D <absolute_path>` to install the plugin
6. Report the results here

Thank you.

**Comment by VladimirMikulic** [comment]
I've tested the changes and merged them, they are good to go :+1:

**Comment by oberonlai** [comment]
I've tested and worked perfectly. You really did a good job and huge favor for me. Thanks a lot again!!! 🙇

**Comment by VladimirMikulic** [comment]
No problem. It's nice to see that you are satisfied :+1:
